import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Qt5Compat.GraphicalEffects

import "../"
import "../buttons"
import "../style"
import "../backgrounds"

Popup {
    id: tipsPopup
    width: 600
    height: 400
    x: (parent.width - width) / 2
    y: (parent.height - height) / 2
    modal: true
    focus: true
    closePolicy: Popup.CloseOnEscape | Popup.CloseOnPressOutside
    visible: results.open

    background: Rectangle {
            color: Universal.background
            radius: 10
            anchors.fill: parent
    }

    onAboutToHide: {
        results.open = false
    }
    
    Label {
        anchors.fill: parent
        text: {"<h3>Three-Phase Power</h3><br>Three-phase power is a common method of electric power transmission and distribution" +
        " that is used to power large motors and other heavy loads. It is also used in residential and commercial buildings to power large appliances and lighting systems.<br>" +
        " A three-phase system consists of three conductors carrying alternating current of the same frequency and voltage amplitude relative to a common reference, but with a phase difference of one third of a cycle between each.<br>" +
        " The voltage generated by three-phase power is typically expressed as a line-to-line voltage. The power delivered by a three-phase system is the same as the power in a single-phase system, but the power is distributed across three phases, which reduces the amount of current required to deliver the same amount of power.<br>" +
        " This reduces the size of the conductors and the amount of power lost in transmission. The three-phase system also allows for the use of three-phase motors, which are more efficient and have a higher power-to-weight ratio than single-phase motors.<br>" +
        " Three-phase power is more efficient and reliable than single-phase power, making it the preferred choice for many applications."}
        wrapMode: Text.WordWrap
    }
}