import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

import "../../components"
import "../../components/buttons"
import "../../components/popups"
import "../../components/style"
import "../../components/visualizers"
import "../../components/exports"
import "../../components/charts"
import "../three_phase/"

import Sine 1.0

Page {
    id: root

    property color textColorPhase: window.modeToggled ? "#ffffff" : "#000000"
    property ThreePhaseSineWaveModel calculator: ThreePhaseSineWaveModel{}

    PopUpText {
        id: popUpText
        parentCard: topHeader
        popupText: "<h3>Three-Phase Power</h3><br>Three-phase power is a common method of electric power transmission and distribution" +
        " that is used to power large motors and other heavy loads. It is also used in residential and commercial buildings to power large appliances and lighting systems.<br>" +
        " A three-phase system consists of three conductors carrying alternating current of the same frequency and voltage amplitude relative to a common reference, but with a phase difference of one third of a cycle between each.<br>" +
        " The voltage generated by three-phase power is typically expressed as a line-to-line voltage. The power delivered by a three-phase system is the same as the power in a single-phase system, but the power is distributed across three phases, which reduces the amount of current required to deliver the same amount of power.<br>" +
        " This reduces the size of the conductors and the amount of power lost in transmission. The three-phase system also allows for the use of three-phase motors, which are more efficient and have a higher power-to-weight ratio than single-phase motors.<br>"
    }

    MessagePopup {
        id: messagePopup
    }

    ScrollView {
        id: scrollView
        anchors.fill: parent
        clip: true
        
        Flickable {
            id: flickableContainer
            contentWidth: parent.width
            contentHeight: mainLayout.height + 10
            bottomMargin: 5
            leftMargin: 5
            rightMargin: 5
            topMargin: 5

            ColumnLayout {
                id: mainLayout
                anchors.centerIn: parent

                // Header with title and help button
                RowLayout {
                    id: topHeader
                    Layout.fillWidth: true
                    Layout.bottomMargin: 5
                    Layout.leftMargin: 5

                    Label {
                        text: "Three-Phase Visualizer"
                        font.pixelSize: 20
                        font.bold: true
                        Layout.fillWidth: true
                    }

                    StyledButton {
                        ToolTip.text: "Export results to PDF"
                        ToolTip.visible: hovered
                        ToolTip.delay: 500
                        
                        Layout.alignment: Qt.AlignRight
                        icon.source: "../../../icons/rounded/download.svg"

                        onClicked: {
                            if (calculator) {
                                calculator.exportToPdf()
                            }
                        }
                    }

                    StyledButton {
                        id: helpButton
                        icon.source: "../../../icons/rounded/info.svg"
                        ToolTip.text: "Information"
                        ToolTip.visible: hovered
                        ToolTip.delay: 500
                        onClicked: popUpText.open()
                    }
                }

                // Mainlayout
                ColumnLayout {
                    RowLayout {
                        id: controls
                        // Controls
                        WaveControls {
                            id: waveControls
                            Layout.minimumHeight: 460
                            Layout.minimumWidth: 500
                            onRequestAutoScale: waveChart.autoScale()
                            calculator: root.calculator //pass calculator to controls
                        }

                        ColumnLayout {
                            // Measurements
                            WaveCard {
                                id: results
                                title: "Measurements"
                                Layout.minimumHeight: 250
                                Layout.minimumWidth: 410

                                PhaseTable {
                                    anchors.fill: parent
                                    anchors.margins: 10
                                    calculator: root.calculator //pass calculator to chart
                                }
                            }

                            // Sequence components
                            WaveCard {
                                title: "Sequence Components"
                                Layout.minimumWidth: 410
                                Layout.minimumHeight: 180
                                Layout.alignment: Qt.AlignTop
                                Layout.fillHeight: true
                                
                                GridLayout {
                                    anchors.top: parent.top
                                    anchors.left: parent.left
                                    anchors.right: parent.right

                                    columns: 3
                                    
                                    // Headers
                                    Label { text: "Component"; font.bold: true }
                                    Label { text: "Voltage"; font.bold: true }
                                    Label { text: "Current"; font.bold: true }
                                    
                                    // Positive Sequence
                                    Label { text: "Positive:" }
                                    Label { 
                                        text: calculator.positiveSeq.toFixed(1) + " V" 
                                    }
                                    Label { 
                                        text: calculator.positiveSeqCurrent.toFixed(1) + " A" 
                                    }
                                    
                                    // Negative Sequence
                                    Label { text: "Negative:" }
                                    Label { 
                                        text: calculator.negativeSeq.toFixed(1) + " V"
                                        color: calculator.negativeSeq > 5 ? "#ff4444" : textColorPhase
                                    }
                                    Label { 
                                        text: calculator.negativeSeqCurrent.toFixed(1) + " A"
                                        color: calculator.negativeSeqCurrent / calculator.positiveSeqCurrent > 0.1 ? "#ff4444" : textColorPhase
                                    }
                                    
                                    // Zero Sequence
                                    Label { text: "Zero:" }
                                    Label { 
                                        text: calculator.zeroSeq.toFixed(1) + " V"
                                        color: calculator.zeroSeq > 5 ? "#ff4444" : textColorPhase
                                    }
                                    Label { 
                                        text: calculator.zeroSeqCurrent.toFixed(1) + " A"
                                        color: calculator.zeroSeqCurrent > 0.1 ? "#ff4444" : textColorPhase
                                    }
                                    
                                    // Unbalance
                                    Label { text: "Unbalance (%):" }
                                    Label { 
                                        text: (calculator.negativeSeq / calculator.positiveSeq * 100).toFixed(1) + "%"
                                        color: calculator.negativeSeq / calculator.positiveSeq > 0.02 ? "#ff4444" : textColorPhase
                                    }
                                    Label { 
                                        text: (calculator.negativeSeqCurrent / calculator.positiveSeqCurrent * 100).toFixed(1) + "%"
                                        color: calculator.negativeSeqCurrent / calculator.positiveSeqCurrent > 0.1 ? "#ff4444" : textColorPhase
                                    }
                                }
                            }
                        }

                        // Power Analysis
                        WaveCard {
                            title: "Power Analysis"
                            Layout.fillHeight: true
                            Layout.minimumHeight: 460
                            Layout.minimumWidth: 500

                            ColumnLayout {
                                anchors.fill: parent

                                PowerTriangleViz {
                                    Layout.fillWidth: true
                                    Layout.minimumHeight: 250
                                    Layout.minimumWidth: 250
                                    activePower: calculator.activePower
                                    reactivePower: calculator.reactivePower
                                    apparentPower: calculator.apparentPower
                                    powerFactor: calculator.averagePowerFactor
                                    triangleScale: 100
                                    color: window.modeToggled ? "#1a1a1a" : "#f5f5f5"
                                }

                                GridLayout {
                                    columns: 2
                                    Layout.fillWidth: true
                                    Layout.minimumHeight: 100
                                    
                                    Label { text: "Total Apparent Power (S):" }
                                    Label { text: calculator.apparentPower.toFixed(2) + " kVA" }
                                    
                                    Label { text: "Total Active Power (P):" }
                                    Label { text: calculator.activePower.toFixed(2) + " kW" }
                                    
                                    Label { text: "Total Reactive Power (Q):" }
                                    Label { text: calculator.reactivePower.toFixed(2) + " kVAR" }
                                    
                                    Label { text: "System Power Factor:" }
                                    Label { text: calculator.averagePowerFactor.toFixed(3) }
                                }
                            }
                        }
                    }

                    RowLayout {
                        Layout.maximumWidth: controls.width
                        // chart
                        WaveCard {
                            title: "Waveform"
                            Layout.minimumWidth: 600
                            Layout.minimumHeight: 400
                            Layout.fillWidth: true
                            Layout.fillHeight: true
                            
                            WaveChart {
                                id: waveChart
                                anchors.fill: parent
                                anchors.margins: 0

                                calculator: root.calculator //pass calculator to chart
                            }
                        }

                        // Phasor diagram
                        WaveCard {
                            title: "Phasor Diagram"
                            Layout.minimumWidth: 500
                            Layout.minimumHeight: 530
                            Layout.fillHeight: true
                            
                            PhasorDiagram {
                                id: phasorDiagram
                                anchors.fill: parent
                                // Update to include both voltage and current phasors
                                phaseAngles: [
                                    calculator.phaseAngleA,
                                    calculator.phaseAngleB,
                                    calculator.phaseAngleC
                                ]
                                // Add current phasor angles
                                currentPhaseAngles: [
                                    calculator.currentAngleA,
                                    calculator.currentAngleB,
                                    calculator.currentAngleC
                                ]
                                // Add current magnitudes to scale the current phasors properly
                                currentMagnitudes: [
                                    calculator.currentA / 100, // Scale down for visibility
                                    calculator.currentB / 100,
                                    calculator.currentC / 100
                                ]
                                // Add voltage magnitudes
                                voltageMagnitudes: [
                                    calculator.rmsA / 230, // Scale based on default value
                                    calculator.rmsB / 230,
                                    calculator.rmsC / 230
                                ]
                                showCurrentPhasors: true // Flag to enable current phasors
                                
                                // Handle voltage angle changes
                                onAngleChanged: function(index, angle) {
                                    switch(index) {
                                        case 0: calculator.setPhaseAngleA(angle); break;
                                        case 1: calculator.setPhaseAngleB(angle); break;
                                        case 2: calculator.setPhaseAngleC(angle); break;
                                    }
                                }
                                
                                // Handle current angle changes
                                onCurrentAngleChanged: function(index, angle) {
                                    switch(index) {
                                        case 0: calculator.setCurrentAngleA(angle); break;
                                        case 1: calculator.setCurrentAngleB(angle); break;
                                        case 2: calculator.setCurrentAngleC(angle); break;
                                    }
                                }
                                
                                // Handle voltage magnitude changes
                                onMagnitudeChanged: function(index, magnitude) {
                                    let voltageValue = magnitude * 230 * Math.SQRT2;
                                    switch(index) {
                                        case 0: calculator.setAmplitudeA(voltageValue); break;
                                        case 1: calculator.setAmplitudeB(voltageValue); break;
                                        case 2: calculator.setAmplitudeC(voltageValue); break;
                                    }
                                }
                                
                                // Handle current magnitude changes
                                onCurrentMagnitudeChanged: function(index, magnitude) {
                                    try {
                                        // Now we have setters for current in the Python model
                                        if (index === 0) {
                                            calculator.currentA = magnitude;
                                        } else if (index === 1) {
                                            calculator.currentB = magnitude;
                                        } else if (index === 2) {
                                            calculator.currentC = magnitude;
                                        }
                                    } catch (e) {
                                        console.error("Error updating current magnitude:", e);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    Connections {
        target: calculator
        
        function onPdfExportStatusChanged(success, message) {
            if (success) {
                messagePopup.showSuccess(message)
            } else {
                messagePopup.showError(message)
            }
        }
    }
}
