import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Qt5Compat.GraphicalEffects

import Sine 1.0
import components 1.0

import "../components"

Page {
    id: root

    // Add theme-aware text color property
    property color textColor: sideBar.toggle1 ? "#ffffff" : "#000000"

    background: Rectangle {
        color: sideBar.toggle1 ? "#1a1a1a" : "#f5f5f5"
    }

    Popup {
        id: tipsPopup
        width: 600
        height: 400
        x: (parent.width - width) / 2
        y: (parent.height - height) / 2
        modal: true
        focus: true
        closePolicy: Popup.CloseOnEscape | Popup.CloseOnPressOutside
        visible: results.open

        onAboutToHide: {
            results.open = false
        }
        Text {
            anchors.fill: parent
            text: {"<h3>Three-Phase Power</h3><br>Three-phase power is a common method of electric power transmission and distribution" +
            " that is used to power large motors and other heavy loads. It is also used in residential and commercial buildings to power large appliances and lighting systems.<br>" +
            " A three-phase system consists of three conductors carrying alternating current of the same frequency and voltage amplitude relative to a common reference, but with a phase difference of one third of a cycle between each.<br>" +
            " The voltage generated by three-phase power is typically expressed as a line-to-line voltage. The power delivered by a three-phase system is the same as the power in a single-phase system, but the power is distributed across three phases, which reduces the amount of current required to deliver the same amount of power.<br>" +
            " This reduces the size of the conductors and the amount of power lost in transmission. The three-phase system also allows for the use of three-phase motors, which are more efficient and have a higher power-to-weight ratio than single-phase motors.<br>" +
            " Three-phase power is more efficient and reliable than single-phase power, making it the preferred choice for many applications."}
            wrapMode: Text.WordWrap
        }
    }

    ScrollView {
        id: scrollView
        anchors.fill: parent
        clip: true
        
        Flickable {
            contentWidth: parent.width
            contentHeight: mainLayout.height
            bottomMargin : 5
            leftMargin : 5
            rightMargin : 5
            topMargin : 5
            
            RowLayout {
                id: mainLayout
                width: scrollView.width
                anchors.left: parent.left
                spacing: 5

                ColumnLayout {
                    RowLayout {
                        WaveControls {
                            id: waveControls
                            Layout.minimumHeight: 460
                            Layout.minimumWidth: 500
                            onRequestAutoScale: waveChart.autoScale()
                        }

                        WaveCard {
                            title: "Measurements"
                            Layout.minimumHeight: 460
                            Layout.minimumWidth: 370

                            id: results
                            showSettings: true

                            ColumnLayout {
                                anchors.fill: parent
                                anchors.margins: 10
                                spacing: 10

                                PhaseTable {
                                    Layout.fillWidth: true
                                }

                                Rectangle {
                                    Layout.fillWidth: true
                                    height: 1
                                    color: sideBar.toggle1 ? "#404040" : "#e0e0e0"
                                }

                                GridLayout {
                                    columns: 2
                                    columnSpacing: 20
                                    Layout.fillWidth: true
                                    Layout.topMargin: 10

                                    Label { text: "Line-to-Line RMS"; font.bold: true }
                                    Label { text: "Voltage (V)"; font.bold: true }

                                    Label { text: "VAB" }
                                    Label { text: sineModel.rmsAB.toFixed(1) }

                                    Label { text: "VBC" }
                                    Label { text: sineModel.rmsBC.toFixed(1) }

                                    Label { text: "VCA" }
                                    Label { text: sineModel.rmsCA.toFixed(1) }

                                    Item { Layout.columnSpan: 2; Layout.preferredHeight: 10 }

                                    Label { text: "Average Power Factor"; font.bold: true }
                                    Label { 
                                        text: sineModel.averagePowerFactor.toFixed(3)
                                        font.bold: true 
                                    }
                                }
                            }
                        }

                        WaveCard {
                            title: "Sequence Components"
                            Layout.minimumWidth: 400
                            Layout.minimumHeight: 300
                            Layout.alignment: Qt.AlignTop
                            Layout.fillHeight: true
                            
                            GridLayout {
                                // anchors.fill: parent
                                anchors.top: parent.top
                                anchors.left: parent.left
                                anchors.right: parent.right
                                anchors.margins: 10

                                columns: 3
                                rowSpacing: 10
                                columnSpacing: 15
                                
                                // Headers
                                Label { text: "Component"; font.bold: true }
                                Label { text: "Voltage"; font.bold: true }
                                Label { text: "Current"; font.bold: true }
                                
                                // Positive Sequence
                                Label { text: "Positive:" }
                                Label { 
                                    text: sineModel.positiveSeq.toFixed(1) + " V" 
                                    font.bold: true
                                }
                                Label { 
                                    text: sineModel.positiveSeqCurrent.toFixed(1) + " A" 
                                    font.bold: true
                                }
                                
                                // Negative Sequence
                                Label { text: "Negative:" }
                                Label { 
                                    text: sineModel.negativeSeq.toFixed(1) + " V"
                                    font.bold: true 
                                    color: sineModel.negativeSeq > 5 ? "#ff4444" : textColor
                                }
                                Label { 
                                    text: sineModel.negativeSeqCurrent.toFixed(1) + " A"
                                    font.bold: true
                                    color: sineModel.negativeSeqCurrent / sineModel.positiveSeqCurrent > 0.1 ? "#ff4444" : textColor
                                }
                                
                                // Zero Sequence
                                Label { text: "Zero:" }
                                Label { 
                                    text: sineModel.zeroSeq.toFixed(1) + " V"
                                    font.bold: true
                                    color: sineModel.zeroSeq > 5 ? "#ff4444" : textColor
                                }
                                Label { 
                                    text: sineModel.zeroSeqCurrent.toFixed(1) + " A"
                                    font.bold: true
                                    color: sineModel.zeroSeqCurrent > 0.1 ? "#ff4444" : textColor
                                }
                                
                                // Unbalance
                                Label { text: "Unbalance (%):" }
                                Label { 
                                    text: (sineModel.negativeSeq / sineModel.positiveSeq * 100).toFixed(1) + "%"
                                    font.bold: true
                                    color: sineModel.negativeSeq / sineModel.positiveSeq > 0.02 ? "#ff4444" : textColor
                                }
                                Label { 
                                    text: (sineModel.negativeSeqCurrent / sineModel.positiveSeqCurrent * 100).toFixed(1) + "%"
                                    font.bold: true
                                    color: sineModel.negativeSeqCurrent / sineModel.positiveSeqCurrent > 0.1 ? "#ff4444" : textColor
                                }
                            }
                        }

                        WaveCard {
                            title: "Power Analysis"
                            Layout.fillWidth: true
                            Layout.fillHeight: true
                            Layout.minimumHeight: 460
                            Layout.minimumWidth: 400

                            ColumnLayout {
                                anchors.fill: parent

                                PowerTriangle {
                                    Layout.fillWidth: true
                                    Layout.minimumHeight: 250
                                    Layout.minimumWidth: 250
                                    activePower: sineModel.activePower
                                    reactivePower: sineModel.reactivePower
                                    apparentPower: sineModel.apparentPower
                                    powerFactor: sineModel.averagePowerFactor
                                    triangleScale: 100
                                    color: sideBar.toggle1 ? "#1a1a1a" : "#f5f5f5"
                                    textColor: sideBar.toggle1 ? "#ffffff" : "#000000"
                                }

                                GridLayout {
                                    columns: 2
                                    Layout.fillWidth: true
                                    Layout.minimumHeight: 100
                                    
                                    Label { text: "Total Apparent Power (S):" }
                                    Label { text: sineModel.apparentPower.toFixed(2) + " kVA" }
                                    
                                    Label { text: "Total Active Power (P):" }
                                    Label { text: sineModel.activePower.toFixed(2) + " kW" }
                                    
                                    Label { text: "Total Reactive Power (Q):" }
                                    Label { text: sineModel.reactivePower.toFixed(2) + " kVAR" }
                                    
                                    Label { text: "System Power Factor:" }
                                    Label { text: sineModel.averagePowerFactor.toFixed(3) }
                                }
                            }
                        }
                    }

                    RowLayout {
                        WaveCard {
                            title: "Waveform"
                            Layout.minimumWidth: 620
                            Layout.minimumHeight: 400
                            Layout.fillWidth: true
                            Layout.fillHeight: true
                            
                            WaveChart {
                                id: waveChart
                                anchors.fill: parent
                            }
                        }

                        WaveCard {
                            title: "Phasor Diagram"
                            Layout.minimumWidth: 530
                            Layout.minimumHeight: 530
                            Layout.fillHeight: true
                            
                            PhasorDiagram {
                                anchors.fill: parent
                                // Update to include both voltage and current phasors
                                phaseAngles: [
                                    sineModel.phaseAngleA,
                                    sineModel.phaseAngleB,
                                    sineModel.phaseAngleC
                                ]
                                // Add current phasor angles
                                currentPhaseAngles: [
                                    sineModel.currentAngleA,
                                    sineModel.currentAngleB,
                                    sineModel.currentAngleC
                                ]
                                // Add current magnitudes to scale the current phasors properly
                                currentMagnitudes: [
                                    sineModel.currentA / 100, // Scale down for visibility
                                    sineModel.currentB / 100,
                                    sineModel.currentC / 100
                                ]
                                showCurrentPhasors: true // Flag to enable current phasors
                                
                                // Handle voltage angle changes
                                onAngleChanged: function(index, angle) {
                                    switch(index) {
                                        case 0: sineModel.setPhaseAngleA(angle); break;
                                        case 1: sineModel.setPhaseAngleB(angle); break;
                                        case 2: sineModel.setPhaseAngleC(angle); break;
                                    }
                                }
                                
                                // Handle current angle changes
                                onCurrentAngleChanged: function(index, angle) {
                                    switch(index) {
                                        case 0: sineModel.setCurrentAngleA(angle); break;
                                        case 1: sineModel.setCurrentAngleB(angle); break;
                                        case 2: sineModel.setCurrentAngleC(angle); break;
                                    }
                                }
                            }
                        }
                    }                   
                }                
            }
        }
    }
}
